common:
  clusterIssuer: letsencrypt-prod

  defaultImagePullSecrets:
    enabled: true

  cronjob:
    enabled: false

  deployment:
    enabled: true
    port: 80
    replicaCount: 1
    image: ghcr.io/advplyr/audiobookshelf:2.31.0
    nodeSelector:
      kubernetes.io/hostname: slave01
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

  existingClaimVolumeMounts:
  - name: audiobook-config-nfs
    mountPath: /config
    size: 1Gi
    storageClassName: nfs-retain
  - name: audiobook-data-nfs
    mountPath: /metadata/items
    size: 10Gi
    storageClassName: nfs-retain
  - name: audiobook-media-nas
    mountPath: /audiobooks

  service:
    enabled: true
    ports:
    - port: 80
      targetPort: 80
      name: http
  ingress:
    enabled: false
    class: cilium
    hosts:
    - host: bookshelf.nullservers.com
