apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-http-route
  namespace: cilium-gateway-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minio.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium-gateway-system
  hostnames:
  - "minio.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: minio
      namespace: minio
      port: 9001
