apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rustfs-http-route
  namespace: cilium-gateway-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: s3.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium-gateway-system
  hostnames:
  - "s3.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: rustfs
      namespace: rustfs
      port: 8080
