apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-nullservers-com-tls
  namespace: envoy-gateway-system
spec:
  secretName: adguard-nullservers-com-tls-secret # The name of the Kubernetes secret to store the certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - adguard.nullservers.com
  - dns.nullservers.com
