apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adventurelog-frontend-tls
  namespace: envoy-gateway-system
spec:
  secretName: adventurelog-frontend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - trips.nullservers.com
