apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adventurelog-backend-tls
  namespace: envoy-gateway-system
spec:
  secretName: adventurelog-backend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - backend-trips.nullservers.com
