apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: collabora-tls
  namespace: envoy-gateway-system
spec:
  secretName: collabora-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - docs.nullservers.com
