apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flux-tls
  namespace: envoy-gateway-system
spec:
  secretName: flux-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - flux.nullservers.com
