apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glance-tls
  namespace: envoy-gateway-system
spec:
  secretName: glance-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - start.nullservers.com
