apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: joplin-tls
  namespace: envoy-gateway-system
spec:
  secretName: joplin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - notes.nullservers.com
