apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: recipes-tls
  namespace: envoy-gateway-system
spec:
  secretName: recipes-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - recipes.nullservers.com
