apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: victoria-metrics-tls
  namespace: envoy-gateway-system
spec:
  secretName: victoria-metrics-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - logs.nullservers.com
  - grafana.nullservers.com
  - metrics.nullservers.com
