apiVersion: v2
name: node-feature-discovery
type: application
version: 0.1.3
dependencies:
- name: node-feature-discovery
  version: 0.18.3
  repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
