apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adventurelog-frontend-http-route
  namespace: envoy-gateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: trips.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: envoy-gateway
  hostnames:
  - "trips.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: adventurelog-frontend
      namespace: adventurelog
      port: 80
