apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: collabora-http-route
  namespace: envoy-gateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: docs.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: envoy-gateway
  hostnames:
  - "docs.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: collabora-collabora-online
      namespace: collabora
      port: 9980
