apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: glance-http-route
  namespace: envoy-gateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: start.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: envoy-gateway
  hostnames:
  - "start.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: glance
      namespace: glance
      port: 80
