apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-http-route
  namespace: envoy-gateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: photos.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: envoy-gateway
  hostnames:
  - "photos.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: immich-server
      namespace: immich
      port: 2283
