apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud-http-route
  namespace: envoy-gateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: drive.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: envoy-gateway
  hostnames:
  - "drive.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nextcloud
      namespace: nextcloud
      port: 80
