apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex-http-route
  namespace: envoy-gateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: envoy-gateway
  hostnames:
  - "plex.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: plex
      namespace: plex
      port: 80
