apiVersion: v2
name: external-dns
version: 1.0.1
type: application
dependencies:
- name: external-dns
  version: 1.20.0
  repository: https://kubernetes-sigs.github.io/external-dns/
  condition: chart.enabled
