apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
  namespace: cilium-gateway-system
spec:
  secretName: minio-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - minio.nullservers.com
