apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rustfs-tls
  namespace: cilium-gateway-system
spec:
  secretName: rustfs-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - s3.nullservers.com
