apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adventurelog-backend-http-route
  namespace: envoy-gateway-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: backend-trips.nullservers.com
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway-system
  hostnames:
  - "backend-trips.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: adventurelog-backend
      namespace: adventurelog
      port: 8000
  - matches:
    - path:
        type: PathPrefix
        value: /admin
    backendRefs:
    - name: adventurelog-backend
      namespace: adventurelog
      port: 8000
  - matches:
    - path:
        type: PathPrefix
        value: /media
    backendRefs:
    - name: adventurelog-backend
      namespace: adventurelog
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: adventurelog-backend
      namespace: adventurelog
      port: 80
