apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafabna-http-route
  namespace: envoy-gateway-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.nullservers.com
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway-system
  hostnames:
  - "grafana.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: grafana-service
      namespace: victoria-metrics
      port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: victoria-logs-http-route
  namespace: envoy-gateway-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: logs.nullservers.com
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway-system
  hostnames:
  - "logs.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: victoria-metrics-victoria-logs-single-server
      namespace: victoria-metrics
      port: 9428
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: victoria-metrics-http-route
  namespace: envoy-gateway-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: metrics.nullservers.com
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway-system
  hostnames:
  - "metrics.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: vmsingle-victoria-metrics
      namespace: victoria-metrics
      port: 8428
