apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-credentials
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: rustfs-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: rustfs-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: rustfs-credentials
      property: password