apiVersion: v1
kind: PersistentVolume
metadata:
  name: rustfs-data-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-minio
  nfs:
    path: /data/minio/data-rustfs/
    server: nas.nullservers.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: nas-minio
  volumeName: rustfs-data-pv
