apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/manifests/cloudflare
  prune: true
  sourceRef:
    kind: GitRepository
    name: workspace
