apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: database-backup
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/manifests/database-backup
  prune: true
  sourceRef:
    kind: GitRepository
    name: workspace
    namespace: flux-system
  targetNamespace: database-backup
