apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recipes
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/manifests/recipes
  prune: true
  sourceRef:
    kind: GitRepository
    name: workspace
  targetNamespace: recipes
