apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/manifests/vaultwarden
  prune: true
  sourceRef:
    kind: GitRepository
    name: workspace
