apiVersion: v2
name: victoria-metrics
version: 0.1.18
type: application
dependencies:
- name: victoria-metrics-k8s-stack
  version: 0.66.1
  repository: https://victoriametrics.github.io/helm-charts/
- name: grafana-operator
  version: 5.21.4
  repository: oci://ghcr.io/grafana/helm-charts
- name: victoria-logs-single
  version: ">=0.9.7"
  repository: https://victoriametrics.github.io/helm-charts/
