apiVersion: v2
name: intel-device-plugins
version: 0.1.1
type: application
dependencies:
- name: intel-device-plugins-operator
  version: 0.35.0
  repository: https://intel.github.io/helm-charts/
  condition: chart.enabled
- name: intel-device-plugins-gpu
  version: 0.34.1
  repository: https://intel.github.io/helm-charts/
