apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gatewayclass.yaml
- gateway.yaml
- referencegrant.yaml
- vmservicescrape.yaml
- certs/adguard-cert.yaml
- certs/adventurelog-backend-certificate.yaml
- certs/adventurelog-frontend-certificate.yaml
- certs/audiobook-certificate.yaml
- certs/authentik-certificate.yaml
- certs/collabora-certificate.yaml
- certs/duplicati-certificate.yaml
- certs/flux-certificate.yaml
- certs/glance-certificate.yaml
- certs/grafana-certificate.yaml
- certs/home-assistant-certificate.yaml
- certs/hubble-certificate.yaml
- certs/immich-certificate.yaml
- certs/joplin-certificate.yaml
- certs/nextcloud-certificate.yaml
- certs/plex-certificate.yaml
- certs/recipes-certificate.yaml
- certs/router-cert.yaml
- certs/victoria-metrics-certificate.yaml
- http-route/adventurelog-backend.yaml
- http-route/adventurelog.yaml
- http-route/audiobook.yaml
- http-route/collabora.yaml
- http-route/duplicati.yaml
- http-route/flux.yaml
- http-route/glance.yaml
- http-route/home-assistant.yaml
- http-route/hubble.yaml
- http-route/immich.yaml
- http-route/joplin.yaml
- http-route/nextcloud.yaml
- http-route/plex.yaml
- http-route/victoria-metrics.yaml

namespace: envoy-gateway-system
