apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default
  namespace: flux-system
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints: 
      - {}
    - fromEntities:
        - ingress
    - fromCIDRSet:
        - cidr: 192.168.20.0/24
  egress:
    - toEndpoints: 
      - {}
    - toEntities:
        - kube-apiserver
        - cluster
    - toFQDNs:
        - matchPattern: "*.ghcr.io"
        - matchPattern: "*.github.com"
        - matchPattern: "*.github.io"
        - matchName: ghcr.io
        - matchName: github.com
        - matchName: charts.jetstack.io
        - matchName: charts.external-secrets.io
        - matchName: release-assets.githubusercontent.com
        - matchNme: pkg-containers.githubusercontent.com 
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
