apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-http-route
  namespace: flux-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: flux.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium-gateway-system
    sectionName: https-wildcard
  hostnames:
  - "flux.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: capacitor
      port: 9000
