apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-credentials
  namespace: joplin
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: joplin-credentials
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: joplin-db-pwd
      property: password
  - secretKey: username
    remoteRef:
      key: joplin-db-pwd
      property: username
  - secretKey: resend-apikey
    remoteRef:
      key: joplin-smtp-apikey
      property: apikey
