apiVersion: v2
name: external-secrets
description: external-secrets
version: 0.1.2
type: application
dependencies:
- name: external-secrets
  version: 1.0.0
  repository: https://charts.external-secrets.io/
