apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password
  namespace: recipes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: recipes-db-pwd
  data:
  - secretKey: password
    remoteRef:
      key: recipes-db-pwd
      property: password-new
      decodingStrategy: None
  - secretKey: username
    remoteRef:
      key: recipes-db-pwd
      property: username
      decodingStrategy: None
  - secretKey: secret-key
    remoteRef:
      key: recipes-db-pwd
      property: secret-key
      decodingStrategy: None
  - secretKey: email-api-key
    remoteRef:
      key: recipes-db-pwd
      property: email-api-key
      decodingStrategy: None
