apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-recipes-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pgsql-nfs-retail
    volumeAttributes:
      server: nfs.nullservers.com
      share: /data/kubernetes-retain/recipes-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media-pvc
  namespace: recipes
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-retain
  volumeName: pv-recipes-data
