apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-credentials
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: vaultwarden-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-token: "{{ .admin_token }}"
        PUSH_INSTALLATION_ID: "{{ .installation_id  }}"
        PUSH_INSTALLATION_KEY: "{{ .installation_key }}"
        SMTP_PASSWORD: "{{ .smtp_password }}"
        DATABASE_URL: "postgresql://vaultwarden:{{ .database_password }}@pgsql.nullservers.com:5432/vaultwarden"
        SSO_CLIENT_ID: "{{ .sso_client_id }}"
        SSO_CLIENT_SECRET: "{{ .sso_client_secret }}"
  data:
  - secretKey: admin_token
    remoteRef:
      key: vaultwarden-credentials
      property: token
  - secretKey: installation_id
    remoteRef:
      key: vaultwarden-credentials
      property: instalationId
  - secretKey: installation_key
    remoteRef:
      key: vaultwarden-credentials
      property: instalationKey
  - secretKey: smtp_password
    remoteRef:
      key: vaultwarden-credentials
      property: resend-key
  - secretKey: database_password
    remoteRef:
      key: vaultwarden-credentials
      property: dbPassword
  - secretKey: sso_client_id
    remoteRef:
      key: vaultwarden-credentials
      property: ssoClientId
  - secretKey: sso_client_secret
    remoteRef:
      key: vaultwarden-credentials
      property: ssoClientSecret
