apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vaultwarden-http-route
  namespace: vaultwarden
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pm.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium-gateway-system
    sectionName: https-wildcard
  hostnames:
  - "pm.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: vaultwarden
      port: 80
