apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- service.yaml
- deployment.yaml
- pvc.yaml
- cnp.yaml
- credentials.yaml
- http-route.yaml
- referencegrant.yaml

commonLabels:
  app: vaultwarden
  component: vaultwarden-app

namespace: vaultwarden
