---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vaultwarden-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pv-vaultwarden-data-nfs
    volumeAttributes:
      server: nfs.nullservers.com
      share: /data/kubernetes-retain/vaultwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-vaultwarden-data
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-retain
