apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - ingress
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: authentik
    - fromCIDR:
        - "192.168.50.0/24"
        - "192.168.20.0/24"
        - "192.168.200.0/24"
      icmps:
        - fields:
            - family: IPv4
              type: 0
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"        
    - toFQDNs:
        - matchPattern: '*.roborock.com'
        - matchName: api.github.com
        - matchName: github.com
        - matchName: raw.githubusercontent.com
        - matchPattern: "*.tuyaeu.com"
        - matchPattern: "*.*.noaa.gov"
        - matchPattern: "*.met.no"
        - matchPattern: "*.*.met.no"
        - matchPattern: "*.nullservers.com"
        - matchPattern: "*.open-meteo.com"
        - matchPattern: "*.*.radio-browser.info"
        - matchPattern: "*.googleapis.com"
    - toCIDRSet:
        - cidr: "192.168.50.240/32" # DNS
        - cidr: "192.168.200.0/24" # IOT network
        - cidr: "192.168.20.0/24" # default Netowrk
    - toEntities:
        - ingress
