apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audiobook-tls
  namespace: envoy-gateway
spec:
  secretName: audiobook-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - bookshelf.nullservers.com
