apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-tls
  namespace: envoy-gateway
spec:
  secretName: home-assistant-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - home.nullservers.com
