apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-tls
  namespace: envoy-gateway
spec:
  secretName: hubble-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hubble.nullservers.com
