apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tls
  namespace: envoy-gateway
spec:
  secretName: immich-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - photos.nullservers.com
