apiVersion: v2
name: home-assistant
description: Home assistant implementation
version: 0.1.10
type: application
dependencies:
- name: home-assistant
  version: 0.3.30
  repository: http://pajikos.github.io/home-assistant-helm-chart/
