apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      imagePullSecrets:
      - name: plex-dockerhub-token
      nodeSelector:
        kubernetes.io/hostname: slave03
      containers:
      - name: plex-container
        image: linuxserver/plex:1.42.2
        ports:
        - containerPort: 32400
        resources:
          requests:
            memory: 1Gi 
            cpu: 500m
          limits:
            memory: 8Gi
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: VERSION
          value: "docker"
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              key: token
              name: plex-claim-token
        - name: TZ
          value: "Europe/Stockholm"
        volumeMounts:
        - name: nfs-plex-config
          mountPath: /config
        - name: plex-media-movies
          mountPath: /data/media/movies
          readOnly: true
        - name: plex-media-youtube
          mountPath: /data/media/youtube
          readOnly: true
        - name: plex-media-desenhos
          mountPath: /data/media/desenhos
          readOnly: true
        - name: plex-media-series
          mountPath: /data/media/series
          readOnly: true
        - name: plex-transcode
          mountPath: /transcode
      volumes:
      - name: nfs-plex-config
        persistentVolumeClaim:
          claimName: nfs-plex-config
      - name: plex-media-movies
        persistentVolumeClaim:
          claimName: plex-media-movies
      - name: plex-media-youtube
        persistentVolumeClaim:
          claimName: plex-media-youtube
      - name: plex-media-desenhos
        persistentVolumeClaim:
          claimName: plex-media-desenhos
      - name: plex-media-series
        persistentVolumeClaim:
          claimName: plex-media-series
      - name: plex-transcode
        emptyDir:
          sizeLimit: 20Gi
