apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plex

resources:
- pv-config.yaml
- pv-media.yaml
- pvc-config.yaml
- pvc-media.yaml
- service.yaml
- deployment.yaml
- cilium-network-policy.yaml
- external-secret-dockerhub.yaml
- external-secret-plex-claim.yaml
