apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-desenhos
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 4000Gi
  volumeName: plex-media-desenhos
  storageClassName: nas-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-series
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 4000Gi
  volumeName: plex-media-series
  storageClassName: nas-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-youtube
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 4000Gi
  volumeName: plex-media-youtube
  storageClassName: nas-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-movies
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 4000Gi
  volumeName: plex-media-movies
  storageClassName: nas-media