chart:
  enabled: true

common:
  clusterIssuer: letsencrypt-prod

  defaultImagePullSecrets:
    enabled: true

  cronjob:
    enabled: false

  deployment:
    imagePullSecrets: dockerhub-token
    enabled: true
    port: 32400
    replicaCount: 1
    image: linuxserver/plex
    nodeSelector:
      kubernetes.io/hostname: slave03
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 4
        memory: 8Gi
    env:
    - name: PUID
      value: "0"
    - name: PGID
      value: "0"
    - name: VERSION
      value: "docker"
    - name: PLEX_CLAIM
      valueFrom:
        secretKeyRef:
          name: plex-claim-token
          key: token
    - name: TZ
      value: "Stockholm/Europe"

  hostVolumeMounts:
  - mountPath: /dev/dri
    name: quicksync
    hostPath: /dev/dri

  pvcVolumeMounts:

  emptyDirVolumeMounts:
  - mountPath: /transcode
    name: plex-transcode
    size: 10Gi

  existingClaimVolumeMounts:
  - name: nfs-plex-config
    mountPath: /config
  - name: plex-media
    mountPath: /data/media

  service:
    enabled: true
    ports:
    - port: 80
      targetPort: 32400
      name: http
      type: ClusterIP
  ingress:
    enabled: false
    class: cilium
    hosts:
    - host: plex.nullservers.com
