apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

resources:
- serviceaccount-master.yaml
- serviceaccount-replica.yaml
- configmap.yaml
- configmap-health.yaml
- configmap-scripts.yaml
- service-headless.yaml
- service-master.yaml
- service-metrics.yaml
- service-replicas.yaml
- statefulset-master.yaml
- statefulset-replicas.yaml
- ciliumnetpol.yaml
- externalsecret-dockerhub.yaml
- vmservicescrape.yaml
