apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
- ciliumnetworkpolicy.yaml
- externalsecret.yaml
- http-route.yaml
- machine-learning-deployment.yaml
- machine-learning-service.yaml
- pvc-nfs.yaml
- referencegrant.yaml
- server-deployment.yaml
- server-service.yaml
- servicemonitor.yaml

commonLabels:
  app: immich
  component: immich-app

images:
- name: ghcr.io/immich-app/immich-server
  newTag: v2.5.6
- name: ghcr.io/immich-app/immich-machine-learning
  newTag: v2.5.6