apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
- ciliumnetworkpolicy.yaml
- externalsecret.yaml
- machine-learning-deployment.yaml
- machine-learning-service.yaml
- pvc-nfs.yaml
- server-deployment.yaml
- server-service.yaml
- servicemonitor.yaml
