apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adventurelog-frontend-http-route
  namespace: adventurelog
  annotations:
    external-dns.alpha.kubernetes.io/hostname: trips.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium-gateway-system
    sectionName: https-wildcard
  hostnames:
  - "trips.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: adventurelog-frontend
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adventurelog-backend-http-route
  namespace: adventurelog
  annotations:
    external-dns.alpha.kubernetes.io/hostname: backend-trips.nullservers.com
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium-gateway-system
    sectionName: https-wildcard
  hostnames:
  - "backend-trips.nullservers.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: adventurelog-backend
      port: 8000
  - matches:
    - path:
        type: PathPrefix
        value: /admin
    backendRefs:
    - name: adventurelog-backend
      port: 8000
  - matches:
    - path:
        type: PathPrefix
        value: /media
    backendRefs:
    - name: adventurelog-backend
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: adventurelog-backend
      port: 80
