# This ConfigMap is just a way to define the cloudflared config.yaml file in k8s.
# It's useful to define it in k8s, rather than as a stand-alone .yaml file, because
# this lets you use various k8s templating solutions (e.g. Helm charts) to
# parameterize your config, instead of just using string literals.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-config
  namespace: cloudflare
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: k8s
    credentials-file: /etc/cloudflared/creds/credentials.json
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    # Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted, so
    # autoupdate doesn't make sense in Kubernetes. However, outside of Kubernetes, we strongly
    # recommend using autoupdate.
    no-autoupdate: true
    # The `ingress` block tells cloudflared which local service to route incoming
    # requests to. For more about ingress rules, see
    # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
    #
    # Remember, these rules route traffic from cloudflared to a local service. To route traffic
    # from the internet to cloudflared, run `cloudflared tunnel route dns <tunnel> <hostname>`.
    # E.g. `cloudflared tunnel route dns example-tunnel tunnel.example.com`.
    ingress:
    # The first rule proxies traffic to the httpbin sample Service defined in app.yaml
    - hostname: nullservers.com
      service: http://nginx-service.bsk-lead.svc.cluster.local:80
    - hostname: api.nullservers.com
      service: http://bsk-api.bsk-api.svc.cluster.local:80
    - hostname: photos.nullservers.com
      service: http://immich-server.immich.svc.cluster.local:2283
    - hostname: bookshelf.nullservers.com
      service: http://audiobook.audiobook.svc.cluster.local:80
    - hostname: recipes.nullservers.com
      service: http://recipes.recipes.svc.cluster.local:80
    - hostname: start.nullservers.com
      service: http://glance.glance.svc.cluster.local:80
    - hostname: auth.nullservers.com
      service: http://authentik-server.authentik.svc.cluster.local:80
    - hostname: drive.nullservers.com
      service: http://nextcloud.nextcloud.svc.cluster.local:80
    - hostname: rss.nullservers.com
      service: http://freshrss.freshrss.svc.cluster.local:80
    - hostname: docs.nullservers.com
      service: http://collabora-collabora-online.collabora.svc.cluster.local:9980
    - hostname: trips.nullservers.com
      service: http://adventurelog-frontend.adventurelog.svc.cluster.local:80
    - hostname: backend-trips.nullservers.com
      service: http://adventurelog-backend.adventurelog.svc.cluster.local:80
    - hostname: watch.nullservers.com
      service: http://plex.plex.svc.cluster.local:80
    # This rule sends traffic to the built-in hello-world HTTP server. This can help debug connectivity
    # issues. If hello.example.com resolves and tunnel.example.com does not, then the problem is
    # in the connection from cloudflared to your local service, not from the internet to cloudflared.
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
