apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- config.yaml
- cloudflare-tunnel-token.yaml
- ciliumnetpol.yaml
- vm-collector.yaml

commonLabels:
  app: cloudflared

namespace: cloudflare
